pipeline:
  build:
    image: golang:1.17
    commands:
    - make test build

  docker-latest:
    image: plugins/docker
    repo: quay.io/uswitch/heimdall
    registry: quay.io
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
    when:
      event: push
      branch: main

  docker-tagged:
    image: plugins/docker
    repo: quay.io/uswitch/heimdall
    registry: quay.io
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_TAG}
    when:
      event: tag
