apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

commonLabels:
  app: heimdall

configMapGenerator:
- name: heimdall-templates
  files:
  - templates/5xx-rate.tmpl
  - templates/replicas-availability-deployment.tmpl
