apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -skaffold

commonLabels:
  env: skaffold

bases:
- ../../base
- ../../config

images:
- name: quay.io/uswitch/heimdall
  newName: quay.io/uswitch/heimdall-skaffold
